name: Deploy Notablog to mimi.github.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate static site
        run: npx notablog generate

      - name: Checkout target repo (mimi.github.io)
        uses: actions/checkout@v3
        with:
          repository: JiaMimil/mimi.github.io
          path: output
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy generated files
        run: |
          rm -rf output/*
          cp -r public/* output/

      - name: Commit and push
        run: |
          cd output
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from mimipage 🚀" || echo "No changes to commit"
          git push origin main
